### ISSUE TITLE
input sanitization

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/skinnywms#1]
Some inputs make the skinnywms crash, e.g.:
- duplicate data
- unsupported levels

If we want to chain the WMS to our current operational procedures we could add some sw layer to  check (and maybe prepare) existing data.
This should probably be external to the skinnywms project altought it could benefit some integration (e.g.: reading the currently supported `LEVELS_TYPE` and `GRID_TYPE` from skinnywms/grib_bindings/GribField.py)

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
