### ISSUE TITLE
Restore field overlay in client (or change client)

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/skinnywms#2]
Should we refine the example client until it's still generalized but suits our needs or should we develop a new web client altogether?

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
